In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('challenge-1-beijing.csv')

In [5]:
df.head(10)

   公交  写字楼  医院  商场  地铁  学校       小区名字  建造时间    房型  楼层  每平米价格   面积
0  18   18  10   0   2  49       远洋山水  2006  2室1厅  26  60937   96
1  17   42  10   0   4  37        椿树园  1998  3室1厅  14  88686  130
2  18   36   9   0   1  24       永乐小区  1989  3室1厅  18  46621   74
3  15   49  13   0   2  45       主语家园  2007  4室3厅   2  86147  462
4   6    0   0   0   0   0       天伦锦城  2007  1室1厅  13  42500   64
5   2    0   0   0   0   0      温哥华森林  2007  5室3厅   3  28368  423
6   0    0   0   0   0   0        晴翠园  2006  5室3厅   3  97646  399
7   4    0   0   0   0   0       启迪香山  2016  2室2厅   9  57083   48
8  18    0   0   0   0  39  亚奥·观典国际公寓  2008  3室2厅  25  61111  180
9   0    0   0   0   0   0      上上城四期  2010  2室1厅  28  26627   86

- **the features**(chinese characters) we choose include public transport, office, hospital, shopping mall, subway, school, construction time, floor and area - total nine items. We note that 
- per-square-meter price is **the target value**.

In [12]:
features = df[df.columns[[0,1 ,2,3, 4,5,7,9,11]]]
features.head(10)

   公交  写字楼  医院  商场  地铁  学校  建造时间  楼层   面积
0  18   18  10   0   2  49  2006  26   96
1  17   42  10   0   4  37  1998  14  130
2  18   36   9   0   1  24  1989  18   74
3  15   49  13   0   2  45  2007   2  462
4   6    0   0   0   0   0  2007  13   64
5   2    0   0   0   0   0  2007   3  423
6   0    0   0   0   0   0  2006   3  399
7   4    0   0   0   0   0  2016   9   48
8  18    0   0   0   0  39  2008  25  180
9   0    0   0   0   0   0  2010  28   86

In [14]:
target = df.iloc[: ,10]
target.head(10)

0    60937
1    88686
2    46621
3    86147
4    42500
5    28368
6    97646
7    57083
8    61111
9    26627
Name: 每平米价格, dtype: int64

In [15]:
pd.concat([features, target], axis=1).head()

   公交  写字楼  医院  商场  地铁  学校  建造时间  楼层   面积  每平米价格
0  18   18  10   0   2  49  2006  26   96  60937
1  17   42  10   0   4  37  1998  14  130  88686
2  18   36   9   0   1  24  1989  18   74  46621
3  15   49  13   0   2  45  2007   2  462  86147
4   6    0   0   0   0   0  2007  13   64  42500

In [19]:
x_train , x_test , y_train , y_test = train_test_split(features , target , test_size = 0.3 , random_state = 42)

In [20]:
len(x_train), len(x_test), len(y_train), len(y_test)

(2100, 900, 2100, 900)

In [24]:
model = LinearRegression()
model.fit(x_train, y_train)

intercept = model.intercept_
coefficients = model.coef_

- we introduce another evaluation indicator, which is average absolute percentage error **MAPE**
- **MAPE** is a variant of MAE, which is a percentage value and, therefore, is easier to understand than other statistics

In [27]:
def mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [28]:
y_true = y_test.values
y_pred = model.predict(x_test)
mape(y_true, y_pred)

np.float64(46.95559808873635)

the result of **MAPE** value is larger -> predicted offset is larger 
that happened for 2 resaons 
- the data has not been processed
- LR is very simple and basic prediction method